CREATE database demo_jpa;
use demo_jpa;
select * from Person;
select * from maison;
select * from address;
select * from departement;
select * from employee;
select * from post;
select * from tag;
select * from post_tag;
